/** 100 sample words with Vietnamese meanings for initializing flashcards. */
export const SEED_WORDS: { word: string; meaning: string }[] = [
  { word: "abandon", meaning: "Bỏ rơi; từ bỏ hoàn toàn" },
  { word: "ability", meaning: "Khả năng; năng lực làm việc gì đó" },
  { word: "absorb", meaning: "Hấp thụ; thấm vào" },
  { word: "abstract", meaning: "Trừu tượng; tồn tại trong ý nghĩ không phải dạng vật chất" },
  { word: "abundant", meaning: "Dồi dào; có số lượng lớn" },
  { word: "accurate", meaning: "Chính xác; đúng trong mọi chi tiết" },
  { word: "achieve", meaning: "Đạt được; thành công đạt mục tiêu" },
  { word: "acknowledge", meaning: "Thừa nhận; chấp nhận điều gì đó tồn tại" },
  { word: "acquire", meaning: "Thu được; có được" },
  { word: "adapt", meaning: "Thích nghi; thay đổi cho phù hợp điều kiện mới" },
  { word: "adequate", meaning: "Đủ; đáp ứng nhu cầu" },
  { word: "adjust", meaning: "Điều chỉnh; thay đổi nhỏ để cải thiện" },
  { word: "admire", meaning: "Ngưỡng mộ; tôn trọng hoặc tán thưởng" },
  { word: "admit", meaning: "Thú nhận; cho phép vào" },
  { word: "advance", meaning: "Tiến lên; tiến bộ" },
  { word: "advantage", meaning: "Lợi thế; điều kiện đặt mình vào vị thế tốt hơn" },
  { word: "advice", meaning: "Lời khuyên; sự hướng dẫn" },
  { word: "affect", meaning: "Ảnh hưởng đến" },
  { word: "afford", meaning: "Đủ khả năng (tiền hoặc thời gian)" },
  { word: "aggressive", meaning: "Hung hăng; sẵn sàng tấn công hoặc đối đầu" },
  { word: "agree", meaning: "Đồng ý; có cùng quan điểm" },
  { word: "aim", meaning: "Mục tiêu; mục đích" },
  { word: "allow", meaning: "Cho phép; để điều gì xảy ra" },
  { word: "alter", meaning: "Thay đổi; sửa đổi" },
  { word: "amount", meaning: "Số lượng" },
  { word: "analyze", meaning: "Phân tích; xem xét chi tiết" },
  { word: "ancient", meaning: "Cổ xưa; từ quá khứ xa xôi" },
  { word: "announce", meaning: "Công bố; làm điều gì được biết công khai" },
  { word: "annual", meaning: "Hàng năm; diễn ra mỗi năm một lần" },
  { word: "anxious", meaning: "Lo lắng; bồn chồn" },
  { word: "apologize", meaning: "Xin lỗi" },
  { word: "apparent", meaning: "Rõ ràng; hiển nhiên" },
  { word: "appeal", meaning: "Kêu gọi; thu hút" },
  { word: "approach", meaning: "Tiếp cận; cách xử lý vấn đề" },
  { word: "approve", meaning: "Phê duyệt; chính thức đồng ý" },
  { word: "approximate", meaning: "Xấp xỉ; gần đúng" },
  { word: "argue", meaning: "Tranh luận; đưa lý do cho hoặc chống lại" },
  { word: "arise", meaning: "Phát sinh; nổi lên" },
  { word: "arrange", meaning: "Sắp xếp; lên kế hoạch" },
  { word: "arrest", meaning: "Bắt giữ; bắt người theo thẩm quyền pháp luật" },
  { word: "assess", meaning: "Đánh giá; ước lượng" },
  { word: "assign", meaning: "Giao việc; phân công nhiệm vụ" },
  { word: "assist", meaning: "Hỗ trợ; giúp đỡ" },
  { word: "assume", meaning: "Giả định; cho rằng không cần chứng minh" },
  { word: "attempt", meaning: "Cố gắng; thử làm điều gì" },
  { word: "attend", meaning: "Tham dự; có mặt tại" },
  { word: "attitude", meaning: "Thái độ; cách nghĩ hoặc cảm nhận" },
  { word: "attract", meaning: "Thu hút; lôi cuốn sự chú ý" },
  { word: "audience", meaning: "Khán giả; người xem hoặc nghe" },
  { word: "average", meaning: "Trung bình; mức điển hình" },
  { word: "avoid", meaning: "Tránh; giữ khoảng cách" },
  { word: "aware", meaning: "Ý thức; có hiểu biết hoặc nhận thức" },
  { word: "balance", meaning: "Cân bằng; giữ ổn định" },
  { word: "barrier", meaning: "Rào cản; thứ chặn hoặc ngăn" },
  { word: "basic", meaning: "Cơ bản; thiết yếu" },
  { word: "behavior", meaning: "Hành vi; cách cư xử" },
  { word: "belief", meaning: "Niềm tin; điều được chấp nhận là đúng" },
  { word: "benefit", meaning: "Lợi ích; lợi thế hoặc lợi nhuận" },
  { word: "brief", meaning: "Ngắn gọn; thời gian ngắn" },
  { word: "brilliant", meaning: "Xuất sắc; rất sáng hoặc thông minh" },
  { word: "budget", meaning: "Ngân sách; kế hoạch chi tiêu" },
  { word: "capable", meaning: "Có khả năng; có thể làm được" },
  { word: "capacity", meaning: "Sức chứa; lượng tối đa có thể chứa" },
  { word: "capture", meaning: "Bắt giữ; chiếm lấy" },
  { word: "category", meaning: "Danh mục; nhóm hoặc loại" },
  { word: "cause", meaning: "Nguyên nhân; thứ gây ra kết quả" },
  { word: "challenge", meaning: "Thử thách; mời cạnh tranh" },
  { word: "character", meaning: "Tính cách; phẩm chất định nghĩa con người" },
  { word: "circumstance", meaning: "Hoàn cảnh; điều kiện ảnh hưởng tình huống" },
  { word: "civil", meaning: "Dân sự; lịch sự" },
  { word: "claim", meaning: "Tuyên bố; yêu cầu" },
  { word: "clarify", meaning: "Làm rõ; giải thích dễ hiểu" },
  { word: "classic", meaning: "Kinh điển; chất lượng cao, truyền thống" },
  { word: "climate", meaning: "Khí hậu; điều kiện thời tiết trong thời gian dài" },
  { word: "collapse", meaning: "Sụp đổ; đổ xuống đột ngột" },
  { word: "colleague", meaning: "Đồng nghiệp" },
  { word: "combine", meaning: "Kết hợp; trộn hoặc ghép lại" },
  { word: "comment", meaning: "Nhận xét; ý kiến" },
  { word: "commission", meaning: "Hoa hồng; nhiệm vụ chính thức" },
  { word: "commit", meaning: "Cam kết; thực hiện điều gì" },
  { word: "communicate", meaning: "Giao tiếp; chia sẻ thông tin" },
  { word: "community", meaning: "Cộng đồng; nhóm người cùng khu vực" },
  { word: "compare", meaning: "So sánh; chỉ ra điểm giống và khác" },
  { word: "compete", meaning: "Cạnh tranh; cố giành chiến thắng" },
  { word: "complex", meaning: "Phức tạp; gồm nhiều phần" },
  { word: "concept", meaning: "Khái niệm; ý tưởng trừu tượng" },
  { word: "concern", meaning: "Lo ngại; điều quan trọng" },
  { word: "conclude", meaning: "Kết luận; kết thúc hoặc quyết định" },
  { word: "condition", meaning: "Điều kiện; tình trạng" },
  { word: "conduct", meaning: "Tiến hành; hành vi" },
  { word: "conference", meaning: "Hội nghị; cuộc họp chính thức" },
  { word: "confirm", meaning: "Xác nhận; chứng minh sự thật" },
  { word: "conflict", meaning: "Xung đột; bất đồng hoặc chiến đấu" },
  { word: "confuse", meaning: "Gây nhầm lẫn; làm ai đó không suy nghĩ rõ" },
  { word: "connect", meaning: "Kết nối; nối hoặc liên kết" },
  { word: "consequence", meaning: "Hậu quả; kết quả của hành động" },
  { word: "consider", meaning: "Cân nhắc; suy nghĩ kỹ" },
  { word: "consist", meaning: "Bao gồm; được tạo thành từ" },
  { word: "constant", meaning: "Liên tục; không ngừng" },
  { word: "construct", meaning: "Xây dựng; tạo ra" },
  { word: "consume", meaning: "Tiêu thụ; dùng hết hoặc ăn" },
  { word: "contact", meaning: "Liên hệ; giao tiếp hoặc chạm" },
  { word: "contain", meaning: "Chứa; bao gồm" },
  { word: "context", meaning: "Bối cảnh; hoàn cảnh xung quanh" },
  { word: "continue", meaning: "Tiếp tục; duy trì làm điều gì" },
  { word: "contract", meaning: "Hợp đồng; thu nhỏ lại" },
  { word: "contrast", meaning: "Tương phản; sự khác biệt giữa hai thứ" },
  { word: "contribute", meaning: "Đóng góp; cho hoặc thêm vào" },
  { word: "control", meaning: "Kiểm soát; có quyền lực, điều chỉnh" },
  { word: "convenient", meaning: "Tiện lợi; phù hợp nhu cầu" },
  { word: "convince", meaning: "Thuyết phục; làm ai đó tin" },
  { word: "cooperate", meaning: "Hợp tác; làm việc cùng nhau" },
  { word: "create", meaning: "Tạo ra; làm nảy sinh" },
  { word: "credit", meaning: "Công nhận; tiền có thể vay" },
  { word: "culture", meaning: "Văn hóa; phong tục và nghệ thuật của xã hội" },
  { word: "current", meaning: "Hiện tại; thuộc thời điểm hiện tại" },
  { word: "declare", meaning: "Tuyên bố; công bố chính thức" },
  { word: "decline", meaning: "Suy giảm; từ chối" },
  { word: "demonstrate", meaning: "Chứng minh; thể hiện rõ" },
  { word: "deny", meaning: "Phủ nhận; từ chối thừa nhận hoặc cho phép" },
  { word: "depend", meaning: "Phụ thuộc; dựa vào" },
  { word: "describe", meaning: "Mô tả; kể bằng lời" },
  { word: "design", meaning: "Thiết kế; lên kế hoạch hoặc tạo cho mục đích" },
  { word: "desire", meaning: "Khao khát; mong muốn mạnh mẽ" },
  { word: "determine", meaning: "Xác định; quyết định hoặc tìm ra" },
  { word: "develop", meaning: "Phát triển; lớn lên hoặc làm lớn lên" },
  { word: "device", meaning: "Thiết bị; công cụ hoặc máy móc" },
  { word: "difference", meaning: "Sự khác biệt; điểm hoặc cách mà mọi thứ khác nhau" },
  { word: "difficult", meaning: "Khó; khó làm hoặc hiểu" },
  { word: "dimension", meaning: "Chiều; phạm vi đo được (dài, rộng...)" },
  { word: "discuss", meaning: "Thảo luận; nói chi tiết" },
  { word: "display", meaning: "Trưng bày; thể hiện" },
  { word: "distribute", meaning: "Phân phối; chia ra hoặc lan rộng" },
  { word: "document", meaning: "Tài liệu; bản ghi bằng văn bản" },
  { word: "element", meaning: "Thành phần; phần cơ bản của cái gì" },
  { word: "emphasize", meaning: "Nhấn mạnh; cho tầm quan trọng đặc biệt" },
  { word: "enable", meaning: "Cho phép; tạo khả năng làm điều gì" },
  { word: "energy", meaning: "Năng lượng; sức để làm việc hoặc hoạt động" },
  { word: "engage", meaning: "Tham gia; chiếm (thời gian/sự chú ý)" },
  { word: "enhance", meaning: "Nâng cao; cải thiện hoặc tăng" },
  { word: "ensure", meaning: "Đảm bảo; làm cho chắc chắn" },
  { word: "environment", meaning: "Môi trường; xung quanh hoặc điều kiện" },
  { word: "establish", meaning: "Thiết lập; tạo dựng" },
  { word: "estimate", meaning: "Ước lượng; tính hoặc đánh giá gần đúng" },
  { word: "evaluate", meaning: "Đánh giá; xem xét và nhận định" },
  { word: "evidence", meaning: "Bằng chứng; sự thật hoặc dấu hiệu chứng tỏ điều gì đúng" },
  { word: "evolve", meaning: "Tiến hóa; phát triển dần" },
  { word: "examine", meaning: "Kiểm tra; xem xét kỹ" },
  { word: "exceed", meaning: "Vượt quá; lớn hơn" },
  { word: "expand", meaning: "Mở rộng; trở nên lớn hơn" },
  { word: "expect", meaning: "Mong đợi; coi là có khả năng" },
  { word: "experience", meaning: "Kinh nghiệm; kiến thức từ việc làm hoặc sống" },
  { word: "experiment", meaning: "Thí nghiệm; kiểm tra khoa học" },
  { word: "explore", meaning: "Khám phá; đi hoặc điều tra" },
  { word: "express", meaning: "Thể hiện; bộc lộ hoặc cho biết" },
  { word: "extend", meaning: "Mở rộng; làm dài hoặc lớn hơn" },
  { word: "factor", meaning: "Nhân tố; điều ảnh hưởng kết quả" },
  { word: "feature", meaning: "Đặc điểm; nét đặc trưng" },
  { word: "focus", meaning: "Tập trung; trung tâm của sự chú ý" },
  { word: "function", meaning: "Chức năng; mục đích hoặc vai trò; hoạt động" },
  { word: "generate", meaning: "Tạo ra; sản xuất" },
  { word: "grant", meaning: "Cấp; cho hoặc cho phép" },
  { word: "guarantee", meaning: "Bảo đảm; lời hứa hoặc cam kết chính thức" },
  { word: "identify", meaning: "Nhận dạng; nhận ra hoặc gọi tên" },
  { word: "impact", meaning: "Tác động; ảnh hưởng mạnh" },
  { word: "implement", meaning: "Triển khai; đưa vào thực hiện" },
  { word: "imply", meaning: "Ngụ ý; gợi ý mà không nói rõ" },
  { word: "improve", meaning: "Cải thiện; làm hoặc trở nên tốt hơn" },
  { word: "include", meaning: "Bao gồm; chứa như một phần" },
  { word: "indicate", meaning: "Chỉ ra; chỉ hoặc thể hiện" },
  { word: "individual", meaning: "Cá nhân; từng người" },
  { word: "influence", meaning: "Ảnh hưởng; sức mạnh tác động lên người khác" },
  { word: "initial", meaning: "Ban đầu; tồn tại ở điểm bắt đầu" },
  { word: "interpret", meaning: "Giải thích; làm rõ ý nghĩa" },
  { word: "involve", meaning: "Liên quan; bao gồm hoặc đòi hỏi" },
  { word: "issue", meaning: "Vấn đề; chủ đề" },
  { word: "item", meaning: "Mục; một thứ trong danh sách hoặc bộ sưu tập" },
  { word: "maintain", meaning: "Duy trì; giữ ở tình trạng tốt" },
  { word: "major", meaning: "Chính; quan trọng hoặc đáng kể" },
  { word: "method", meaning: "Phương pháp; cách làm điều gì" },
  { word: "occur", meaning: "Xảy ra" },
  { word: "opportunity", meaning: "Cơ hội; dịp để làm điều gì" },
  { word: "option", meaning: "Lựa chọn" },
  { word: "participate", meaning: "Tham gia" },
  { word: "particular", meaning: "Cụ thể; riêng biệt" },
  { word: "period", meaning: "Giai đoạn; khoảng thời gian" },
  { word: "policy", meaning: "Chính sách; bộ quy tắc hoặc kế hoạch" },
  { word: "potential", meaning: "Tiềm năng; khả năng tiềm ẩn" },
  { word: "previous", meaning: "Trước đó; đến trước" },
  { word: "primary", meaning: "Chính; quan trọng nhất; đầu tiên" },
  { word: "principle", meaning: "Nguyên tắc; chân lý hoặc quy tắc cơ bản" },
  { word: "process", meaning: "Quy trình; chuỗi các bước" },
  { word: "professional", meaning: "Chuyên nghiệp; liên quan nghề nghiệp; có kỹ năng" },
  { word: "project", meaning: "Dự án; công việc có kế hoạch" },
  { word: "promote", meaning: "Thúc đẩy; khuyến khích hoặc đề bạt" },
  { word: "provide", meaning: "Cung cấp; cho hoặc cung cấp" },
  { word: "purchase", meaning: "Mua" },
  { word: "purpose", meaning: "Mục đích; lý do của điều gì" },
  { word: "quality", meaning: "Chất lượng; tiêu chuẩn của cái gì" },
  { word: "range", meaning: "Phạm vi; giới hạn mà cái gì đó thay đổi" },
  { word: "rate", meaning: "Tỷ lệ; mức độ hoặc tốc độ" },
  { word: "reason", meaning: "Lý do; nguyên nhân hoặc giải thích" },
  { word: "recognize", meaning: "Nhận ra; xác định từ kinh nghiệm trước" },
  { word: "recommend", meaning: "Đề xuất; gợi ý là tốt" },
  { word: "reduce", meaning: "Giảm; làm nhỏ hoặc ít hơn" },
  { word: "refer", meaning: "Đề cập; hướng dẫn đến" },
  { word: "reflect", meaning: "Suy ngẫm; phản chiếu ánh sáng" },
  { word: "region", meaning: "Khu vực; vùng" },
  { word: "relate", meaning: "Liên quan; kết nối hoặc kể" },
  { word: "release", meaning: "Phát hành; thả ra hoặc công bố" },
  { word: "remove", meaning: "Loại bỏ; lấy đi" },
  { word: "replace", meaning: "Thay thế; chiếm chỗ của" },
  { word: "require", meaning: "Yêu cầu; cần" },
  { word: "research", meaning: "Nghiên cứu; tìm hiểu có hệ thống" },
  { word: "resource", meaning: "Nguồn lực; nguồn có thể sử dụng" },
  { word: "respond", meaning: "Phản hồi; trả lời hoặc phản ứng" },
  { word: "restore", meaning: "Khôi phục; đưa về trạng thái ban đầu" },
  { word: "restrict", meaning: "Hạn chế; giới hạn" },
  { word: "result", meaning: "Kết quả; hậu quả hoặc tác động" },
  { word: "reveal", meaning: "Tiết lộ; làm cho biết" },
  { word: "review", meaning: "Xem lại; kiểm tra lại" },
  { word: "role", meaning: "Vai trò; chức năng hoặc phần đảm nhiệm" },
  { word: "section", meaning: "Phần; bộ phận riêng biệt" },
  { word: "select", meaning: "Chọn" },
  { word: "significant", meaning: "Đáng kể; quan trọng" },
  { word: "similar", meaning: "Tương tự; giống nhau" },
  { word: "source", meaning: "Nguồn; xuất xứ hoặc nguyên nhân" },
  { word: "specific", meaning: "Cụ thể; được xác định rõ" },
  { word: "strategy", meaning: "Chiến lược; kế hoạch hành động" },
  { word: "structure", meaning: "Cấu trúc; cách các phần được sắp xếp" },
  { word: "submit", meaning: "Nộp; trình để xem xét" },
  { word: "substitute", meaning: "Thay thế; người/vật thay thế" },
  { word: "succeed", meaning: "Thành công; đạt mục tiêu" },
  { word: "suggest", meaning: "Đề xuất; đưa ra ý tưởng" },
  { word: "summary", meaning: "Tóm tắt; bản tóm lược các ý chính" },
  { word: "support", meaning: "Hỗ trợ; ủng hộ" },
  { word: "survey", meaning: "Khảo sát; tổng quan" },
  { word: "symbol", meaning: "Biểu tượng; thứ đại diện cho thứ khác" },
  { word: "target", meaning: "Mục tiêu; đích cần hướng tới" },
  { word: "task", meaning: "Nhiệm vụ; công việc cần làm" },
  { word: "technique", meaning: "Kỹ thuật; cách làm điều gì" },
  { word: "technology", meaning: "Công nghệ; ứng dụng kiến thức khoa học" },
  { word: "temporary", meaning: "Tạm thời; kéo dài có giới hạn" },
  { word: "theory", meaning: "Lý thuyết; ý tưởng giải thích điều gì" },
  { word: "tradition", meaning: "Truyền thống; phong tục lâu đời" },
  { word: "transfer", meaning: "Chuyển; di chuyển từ nơi này sang nơi khác" },
  { word: "transform", meaning: "Chuyển đổi; thay đổi hoàn toàn" },
  { word: "transport", meaning: "Vận chuyển; chở từ nơi này sang nơi khác" },
  { word: "trend", meaning: "Xu hướng; hướng thay đổi chung" },
  { word: "typical", meaning: "Điển hình; có đặc điểm thường thấy" },
  { word: "unique", meaning: "Độc nhất; chỉ có một loại" },
  { word: "universal", meaning: "Phổ quát; áp dụng cho tất cả" },
  { word: "various", meaning: "Đa dạng; khác nhau" },
  { word: "version", meaning: "Phiên bản; dạng cụ thể của cái gì" },
  { word: "volume", meaning: "Khối lượng; âm lượng" },
  { word: "widespread", meaning: "Lan rộng; có ở nhiều nơi" },
];
